import Head from "next/head";
import Image from "next/image";
import Imagenes from "../components/images";
import styles from "../styles/Home.module.css";
import Granim from "granim";
import { useEffect } from "react";
import fondo from "../public/paisaje.jpg";
export default function Home() {

  return (
    <div
      Style="
      position: relative;
      "
    >
      <img
        loader
        src="paisaje.jpg"
        Style="position: fixed;
        
        display: block;
        width: 100%;
        height: 100%;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;"
      />

      <div
        Style="display:flex;flex-direction:column;align-items:center;padding-top:85px;position: relative;
      z-index:1"
      >
        <Head>
          <title>Feliz dia Ma</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1
          className={styles.asd}
          Style="display: block;
            font-size:50px;
"
        >
          Feliz dia Ma!
        </h1>

        <h5 className={styles.asd}>te amamos</h5>

        <Imagenes />
      </div>
    </div>
  );
}

{
  /* <div
      Style="
      position: relative;
      "
    >
      <canvas id="canvas-basic" Style="position: absolute;
    display: block;
    width: 100%;
    height: 100%;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;"    
></canvas> 


 useEffect(() => {
    const granimInstance = new Granim({
      element: "#canvas-basic",
      direction: "left-right",
      isPausedWhenNotInView: false,
      states: {
        "default-state": {
          gradients: [
            ["#ff9966", "#ff5e62"],
            ["#00F260", "#0575E6"],
            ["#e1eec3", "#f05053"],
          ],
        },
      },
    });
  }, []);*/
}
